# Generated by Django 4.0.3 on 2022-03-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date')),
                ('from_date_time', models.DateTimeField(verbose_name='From Date Time')),
                ('to_date_time', models.DateTimeField(verbose_name='To Date Time')),
                ('city', models.CharField(choices=[('Al Anbar', 'Al Anbar'), ('Babylon', 'Babylon'), ('Baghdad', 'Baghdad'), ('Basra', 'Basra'), ('Dhi Qar', 'Dhi Qar'), ('Al-Qādisiyyah', 'Al-Qādisiyyah'), ('Diyala', 'Diyala'), ('Duhok', 'Duhok'), ('Erbil', 'Erbil'), ('Halabja', 'Halabja'), ('Karbala', 'Karbala'), ('Kirkuk', 'Kirkuk'), ('Maysan', 'Maysan'), ('Muthanna', 'Muthanna'), ('Najaf', 'Najaf'), ('Nineveh', 'Nineveh'), ('Saladin', 'Saladin'), ('Sulaymaniyah', 'Sulaymaniyah'), ('Wasit', 'Wasit')], max_length=70, verbose_name='City')),
                ('address', models.CharField(max_length=600, verbose_name='Address')),
                ('total_slot', models.IntegerField(verbose_name='Total Slot')),
                ('speakers', models.ManyToManyField(related_name='events', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
