# Generated by Django 4.0.3 on 2022-03-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_image'),
        ('Events', '0003_alter_event_speakers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(null=True, related_name='events', to='profiles.profile'),
        ),
    ]
