# Generated by Django 4.0.1 on 2022-01-11 08:41

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DataCollector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='IQ')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('street_address', models.CharField(blank=True, max_length=250, null=True)),
                ('province', models.CharField(choices=[('Al Anbar', 'Al Anbar'), ('Babylon', 'Babylon'), ('Baghdad', 'Baghdad'), ('Basra', 'Basra'), ('Dhi Qar', 'Dhi Qar'), ('Al-Qādisiyyah', 'Al-Qādisiyyah'), ('Diyala', 'Diyala'), ('Duhok', 'Duhok'), ('Erbil', 'Erbil'), ('Halabja', 'Halabja'), ('Karbala', 'Karbala'), ('Kirkuk', 'Kirkuk'), ('Maysan', 'Maysan'), ('Muthanna', 'Muthanna'), ('Najaf', 'Najaf'), ('Nineveh', 'Nineveh'), ('Saladin', 'Saladin'), ('Sulaymaniyah', 'Sulaymaniyah'), ('Wasit', 'Wasit')], max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'DataCollector',
                'verbose_name_plural': 'DataCollectors',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('review_title', models.TextField(blank=True, null=True, verbose_name='Review Title')),
                ('review_content', models.TextField(blank=True, null=True, verbose_name='Review Content')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.category')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('old_price', models.PositiveBigIntegerField(blank=True, null=True)),
                ('price', models.PositiveBigIntegerField()),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, help_text='Input Duration In Seconds', null=True)),
                ('lectures', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, choices=[('Arabic', 'Arabic'), ('English', 'English')], default=1, max_length=50, null=True)),
                ('skill_level', models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Advance', 'Advance')], default=1, max_length=50, null=True)),
                ('certificate', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=50, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructors.instructor')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.subcategory')),
            ],
        ),
    ]
