# Generated by Django 4.0.3 on 2022-03-21 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_sub_category_alter_subcategory_category'),
        ('courses', '0002_datacollector_created_at_datacollector_updated_at_and_more'),
    ]

    operations = [
    ]
