# Generated by Django 4.0.3 on 2022-03-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_merge_20220321_0923'),
        ('courses', '0003_merge_20220321_1314'),
    ]

    operations = [
    ]
