# Generated by Django 4.0 on 2021-12-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_duration_alter_course_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.DurationField(blank=True, help_text='input duration in seconds', null=True),
        ),
    ]
