# Generated by Django 4.0.3 on 2022-03-24 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0003_instructor_facebook_instructor_instagram_and_more'),
        ('courses', '0004_merge_20220321_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='instructors.instructor'),
        ),
        migrations.AlterField(
            model_name='datacollector',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
