# Generated by Django 4.0.3 on 2022-03-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_instructor_alter_datacollector_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollector',
            name='phone',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
    ]
