# Generated by Django 4.0 on 2021-12-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lectures',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
