# Generated by Django 4.0 on 2021-12-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_lectures'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(blank=True, choices=[('1', 'arabic'), ('2', 'English')], default=1, max_length=50, null=True),
        ),
    ]
