# Generated by Django 4.0 on 2021-12-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='skill_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('advance', 'Advance')], default=1, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(blank=True, choices=[('Arabic', 'Arabic'), ('English', 'English')], default=1, max_length=50, null=True),
        ),
    ]
