# Generated by Django 4.0 on 2021-12-25 12:58

from django.db import migrations
import ckeditor.fields

class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
