# Generated by Django 4.0 on 2021-12-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_course_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='old_price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.DurationField(blank=True, help_text='Input Duration In Seconds', null=True),
        ),
    ]
