# Generated by Django 4.0.1 on 2022-01-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_datacollector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollector',
            name='street_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
