# Generated by Django 4.0.1 on 2022-01-06 06:39

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_datacollector_street_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollector',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
