# Generated by Django 4.0.1 on 2022-01-06 09:58

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_datacollector_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='review_content',
            field=models.TextField(blank=True, null=True, verbose_name='Review Content'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_title',
            field=models.TextField(blank=True, null=True, verbose_name='Review Title'),
        ),
        migrations.AlterField(
            model_name='datacollector',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='IQ'),
        ),
    ]
