# Generated by Django 4.0.1 on 2022-01-08 10:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_alter_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
