# Generated by Django 4.0 on 2021-12-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
