# Generated by Django 4.0 on 2021-12-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0003_alter_instructor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='specialization',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
